# Generated by Django 4.2.11 on 2026-03-06 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=255)),
                ('transaction_status', models.CharField(max_length=100)),
                ('status_code', models.CharField(max_length=10)),
                ('gross_amount', models.CharField(max_length=50)),
                ('signature_valid', models.BooleanField()),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
